### ISSUE TITLE
Can't change which Mono version is being used

### ISSUE THREAD

**Issue by igorr0driguez** [sublimelsp/LSP-OmniSharp#15]
Symptoms similar to the Unity issue, but I'm opening this specificaly so maybe we can put some attention into the possibility of changing which Mono LSP-Omnisharp is using.

I'm really interested in this since this (SLP-OmniSharp) is currently the only option for Sublime Text users in regards to C#/Unity projects.

I realise it may not be simple and/or easy.

Thanks to all the devs for the hard work.

**Comment by rwols** [comment]
v1.39.0 removed the bundled mono, so we'll have to take care of this anyway: https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.39.0

See: https://github.com/OmniSharp/omnisharp-roslyn/issues/2339

**Comment by deathaxe** [comment]
Obsolete issue as of PR #40.
