### ISSUE TITLE
Custom Omnisharp installation path

### ISSUE THREAD

**Issue by zikaura** [sublimelsp/LSP-OmniSharp#16]
I already have Omnisharp installed in a different location than the default `$DATA/Package Storage/LSP-OmniSharp`, is it possible to change this in a settings variable maybe?

**Comment by rwols** [comment]
I’m open to support this when you create a pull request for this functionality.

**Comment by deathaxe** [comment]
This should be possible by adding `"command"` setting to _LSP-OmniSharp.sublime-settings_

```json
{
    "command": [
        "OmniSharp",
        "--languageserver",
        "--encoding", "utf-8"
    ],
}
```

**Comment by zikaura** [comment]
Thanks !
