### ISSUE TITLE
ability to hide codelenses

### ISSUE THREAD

**Issue by ssoher** [sublimelsp/LSP-OmniSharp#19]
I don't know if code lenses is the correct term, I want to hide the icons that appear on the right side of the lines. Any pointers is much appreciated if this is possible.

![image](https://user-images.githubusercontent.com/4283979/195416896-22ca7baf-f074-4a64-9929-e8b65f278f50.png)

**Comment by rwols** [comment]
You can use the disabled_capabilities setting to achieve this.

**Comment by rwols** [comment]
It’s mentioned here: https://lsp.sublimetext.io/guides/client_configuration/#custom-client-configuration

edit LSP-OmniSharp.sublime-settings

**Comment by rwols** [comment]
disabled_capabilities needs to be a JSON dict, not a JSON array. Key should be codeLensProvider, value should be `true`
