### ISSUE TITLE
Disable Automatic Signature Help

### ISSUE THREAD

**Issue by ssoher** [sublimelsp/LSP-OmniSharp#21]
Is there a way to disable the "signature help" so that it only shows up when I use it's set keybinding for `lsp.signature_help_available`. At the moment the signature help popup (image below) shows up as soon as I type a `(` or a `,` character. `auto_complete` is already set to `false` in my sublime settings.

![image](https://user-images.githubusercontent.com/4283979/198901967-7ba96fca-71bb-492e-9281-31dda5a7640a.png)

**Comment by rchl** [comment]
I believe adding this in LSP Omnisharp settings should do it:

```js
    "disabled_capabilities": {
        "signatureHelpProvider": {
            "triggerCharacters": true
        }
    }
```
