### ISSUE TITLE
`documentHighlightProvider` capability

### ISSUE THREAD

**Issue by ssoher** [sublimelsp/LSP-OmniSharp#24]
I find it useful when other occurances of the symbol under the caret are highlighted, makes it easy seeing the immediate usages. But this doesn't seem to work in LSP-OmniSharp even when I change `document_highlight_style` to `background` and add the related scopes with custom background colors to my color theme (using this as a guide https://lsp.sublimetext.io/customization/#document-highlights).

Do we have the required capability in the server, am I doing something wrong?

**Comment by rwols** [comment]
If you open the LSP log panel with “LSP: Toggle Log Panel”, then you can see what capabilities the server has exactly by looking at the response of the `initialize` request

**Comment by rwols** [comment]
Maybe easier: run `view.run_command("lsp_dump_buffer_capabilities")` in the ST console when you have a .cs file open.

**Comment by ssoher** [comment]
@rwols I can't feel sad now that the answer is no since I've also learned something, thanks :)

Can we consider this "issue" a feature request then?

**Comment by rwols** [comment]
It seems JoeRobich added it just 18 days ago: https://github.com/OmniSharp/omnisharp-roslyn/blob/c214d900ca250556bb09156fcb2b27d217a3a523/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpDocumentHighlightHandler.cs

**Comment by rwols** [comment]
But maybe it's just a placeholder, I haven't looked much into it: https://github.com/OmniSharp/omnisharp-roslyn/pull/2463

**Comment by rwols** [comment]
v1.39.2 should contain that functionality: https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.39.2

**Comment by rwols** [comment]
While we use v1.38.2: https://github.com/sublimelsp/LSP-OmniSharp/blob/1afed47ed5aebc692c6c69220c80ce79b9cebc0f/plugin.py#L15

**Comment by ssoher** [comment]
I can confirm that replacing the packaged omnisharp version with the latest release 1.39.2 does provide highlighting.

**Comment by deathaxe** [comment]
Should be fixed by PR #40, which makes transition to latest .NET 6+ based OmniSharp binaries.
