### ISSUE TITLE
Doesn't Support Top-Level Satements (.NET 6)

### ISSUE THREAD

**Issue by j0of** [sublimelsp/LSP-OmniSharp#27]
I prefer to use .NET 6 when coding in C# so that I don't have to declare `using System;` or the main method, but I get an error whenever I don't. 
![image](https://user-images.githubusercontent.com/124946864/226455579-95b631a9-86b0-41bf-b9f1-ccbc82afbc43.png)

**Comment by beautifulcoder** [comment]
I can verify a .NET 6 project does not work either. So, the problem might be lack of net6.0 support in general.

**Comment by beautifulcoder** [comment]
On further inspection, net6 supports works when you only have the .NET SDK installed on your machine. If you install both Framework, and .NET Core on Windows then only Framework seems to work with Omnisharp. My guess is this more of a msbuild limitation than Omnisharp.

**Comment by deathaxe** [comment]
Should be fixed by PR https://github.com/sublimelsp/LSP-OmniSharp/pull/40, which makes transition to latest .NET 6+ based OmniSharp binaries. They are required to deal with latest .NET projects.
